[phases.setup]
commands = ["cd backend && npm install"]

[phases.build]
commands = ["cd backend && npm run build"]

[phases.start]
commands = ["cd backend && node -r tsconfig-paths/register compiled/backend/src/app.js"]
